### ISSUE TITLE
Pretrained model unavailable

### ISSUE THREAD

**Issue by hoangftran** [hoangIT1/Vietnamese-Punctuation-Restoration#1]
Please upload your pretrained model at [google drive](https://drive.google.com/drive/folders/1pKeP6YGsYveJNiAhl9O8vdG_OAoIx1Gk?usp=sharing), the file seem to be deleted.
Thank you very much.

**Comment by hoangIT1** [comment]
Sorry mate, I have no longer keep these file. You can train model again with GPU in colab by tutorial in Readme.md, it is not waste too much time
